- name: Update server
  hosts: server
  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Upgrade apt
      ansible.builtin.apt:
        upgrade: true
      become: true
